### PR TITLE
Change all internal paths to relative in test files

### PR DESCRIPTION
**Pull request by vitorbal**
Change all internal paths to relative in test files and get rid of `tests/node_modules/redux-router-kit` symlink.

This avoids a weird issue where `npm publish` goes into an infinite loop of `tests/node_modules/redux-router-kit/tests/node_modules/` etc.:

cc @neilff

### CODE REVIEW

**Comment by jdeal** [comment]
Weird. What about just adding `test` to `.npmignore`?

**Comment by vitorbal** [comment]
That makes sense to me too @jdeal, no reason we should be publishing the tests!

**Comment by vitorbal** [comment]
Are you okay with merging the relative path changes too, @jdeal? I feel like that's clearer than the symlink for future maintainers but I'm okay with reverting that part of this PR too if you're feel strongly about it!

**Comment by jdeal** [comment]
I'm cool with the relative paths @vitorbal.

**Pull request merged**
